# Pandas and NumPy Q&A

In [1]:
%pwd

'/Users/whipp/Desktop/Geo-Python'

In [2]:
cd notebooks/notebooks/L5/

/Users/whipp/Desktop/Geo-Python/notebooks/notebooks/L5


In [3]:
ls

Kumpula-June-2016-w-metadata.txt  Pandas/
NumPy/                            img/


# Getting started

In [4]:
import pandas as pd
import numpy as np

In [5]:
# Read in data file using Pandas
fp = 'Kumpula-June-2016-w-metadata.txt'

dataFrame = pd.read_csv(fp, skiprows=8)

In [6]:
print(dataFrame)

    YEARMODA  TEMP   MAX   MIN
0   20160601  65.5  73.6  54.7
1   20160602  65.8  80.8  55.0
2   20160603  68.4  77.9  55.6
3   20160604  57.5  70.9  47.3
4   20160605  51.4  58.3  43.2
5   20160606  52.2  59.7  42.8
6   20160607  56.9  65.1  45.9
7   20160608  54.2  60.4  47.5
8   20160609  49.4  54.1  45.7
9   20160610  49.5  55.9  43.0
10  20160611  54.0  62.1  41.7
11  20160612  55.4  64.2  46.0
12  20160613  58.3  68.2  47.3
13  20160614  59.7  67.8  47.8
14  20160615  63.4  70.3  49.3
15  20160616  57.8  67.5  55.6
16  20160617  60.4  70.7  55.9
17  20160618  57.3  62.8  54.0
18  20160619  56.3  59.2  54.1
19  20160620  59.3  69.1  52.2
20  20160621  62.6  71.4  50.4
21  20160622  61.7  70.2  55.4
22  20160623  60.9  67.1  54.9
23  20160624  61.1  68.9  56.7
24  20160625  65.7  75.4  57.9
25  20160626  69.6  77.7  60.3
26  20160627  60.7  70.0  57.6
27  20160628  65.4  73.0  55.8
28  20160629  65.8  73.2  59.7
29  20160630  65.7  72.7  59.2


In [7]:
# Read data file using NumPy

data = np.genfromtxt(fp, skip_header=9, delimiter=',')

In [8]:
print(data)

[[2.0160601e+07 6.5500000e+01 7.3600000e+01 5.4700000e+01]
 [2.0160602e+07 6.5800000e+01 8.0800000e+01 5.5000000e+01]
 [2.0160603e+07 6.8400000e+01 7.7900000e+01 5.5600000e+01]
 [2.0160604e+07 5.7500000e+01 7.0900000e+01 4.7300000e+01]
 [2.0160605e+07 5.1400000e+01 5.8300000e+01 4.3200000e+01]
 [2.0160606e+07 5.2200000e+01 5.9700000e+01 4.2800000e+01]
 [2.0160607e+07 5.6900000e+01 6.5100000e+01 4.5900000e+01]
 [2.0160608e+07 5.4200000e+01 6.0400000e+01 4.7500000e+01]
 [2.0160609e+07 4.9400000e+01 5.4100000e+01 4.5700000e+01]
 [2.0160610e+07 4.9500000e+01 5.5900000e+01 4.3000000e+01]
 [2.0160611e+07 5.4000000e+01 6.2100000e+01 4.1700000e+01]
 [2.0160612e+07 5.5400000e+01 6.4200000e+01 4.6000000e+01]
 [2.0160613e+07 5.8300000e+01 6.8200000e+01 4.7300000e+01]
 [2.0160614e+07 5.9700000e+01 6.7800000e+01 4.7800000e+01]
 [2.0160615e+07 6.3400000e+01 7.0300000e+01 4.9300000e+01]
 [2.0160616e+07 5.7800000e+01 6.7500000e+01 5.5600000e+01]
 [2.0160617e+07 6.0400000e+01 7.0700000e+01 5.5900000e+0

In [10]:
# First row of data file
data[0,:]

array([2.0160601e+07, 6.5500000e+01, 7.3600000e+01, 5.4700000e+01])

In [11]:
# First column of data file
data[:,0]

array([20160601., 20160602., 20160603., 20160604., 20160605., 20160606.,
       20160607., 20160608., 20160609., 20160610., 20160611., 20160612.,
       20160613., 20160614., 20160615., 20160616., 20160617., 20160618.,
       20160619., 20160620., 20160621., 20160622., 20160623., 20160624.,
       20160625., 20160626., 20160627., 20160628., 20160629., 20160630.])

In [12]:
# Split data into 1D arrays (NumPy)
date = data[:,0]
temp = data[:,1]
max_temp = data[:,2]
min_temp = data[:,3]

In [13]:
print(temp)

[65.5 65.8 68.4 57.5 51.4 52.2 56.9 54.2 49.4 49.5 54.  55.4 58.3 59.7
 63.4 57.8 60.4 57.3 56.3 59.3 62.6 61.7 60.9 61.1 65.7 69.6 60.7 65.4
 65.8 65.7]


In [14]:
# Show temperatures in Pandas
print(dataFrame['TEMP'])

0     65.5
1     65.8
2     68.4
3     57.5
4     51.4
5     52.2
6     56.9
7     54.2
8     49.4
9     49.5
10    54.0
11    55.4
12    58.3
13    59.7
14    63.4
15    57.8
16    60.4
17    57.3
18    56.3
19    59.3
20    62.6
21    61.7
22    60.9
23    61.1
24    65.7
25    69.6
26    60.7
27    65.4
28    65.8
29    65.7
Name: TEMP, dtype: float64


In [15]:
# Create a temperature range variable (or column)

# NumPy
temp_range = max_temp - min_temp

# Pandas
dataFrame['TEMP_RANGE'] = dataFrame['MAX'] - dataFrame['MIN']

In [16]:
# NumPy
print(temp_range)

[18.9 25.8 22.3 23.6 15.1 16.9 19.2 12.9  8.4 12.9 20.4 18.2 20.9 20.
 21.  11.9 14.8  8.8  5.1 16.9 21.  14.8 12.2 12.2 17.5 17.4 12.4 17.2
 13.5 13.5]


In [17]:
# Pandas
print(dataFrame['TEMP_RANGE'])

0     18.9
1     25.8
2     22.3
3     23.6
4     15.1
5     16.9
6     19.2
7     12.9
8      8.4
9     12.9
10    20.4
11    18.2
12    20.9
13    20.0
14    21.0
15    11.9
16    14.8
17     8.8
18     5.1
19    16.9
20    21.0
21    14.8
22    12.2
23    12.2
24    17.5
25    17.4
26    12.4
27    17.2
28    13.5
29    13.5
Name: TEMP_RANGE, dtype: float64


In [18]:
print(dataFrame)

    YEARMODA  TEMP   MAX   MIN  TEMP_RANGE
0   20160601  65.5  73.6  54.7        18.9
1   20160602  65.8  80.8  55.0        25.8
2   20160603  68.4  77.9  55.6        22.3
3   20160604  57.5  70.9  47.3        23.6
4   20160605  51.4  58.3  43.2        15.1
5   20160606  52.2  59.7  42.8        16.9
6   20160607  56.9  65.1  45.9        19.2
7   20160608  54.2  60.4  47.5        12.9
8   20160609  49.4  54.1  45.7         8.4
9   20160610  49.5  55.9  43.0        12.9
10  20160611  54.0  62.1  41.7        20.4
11  20160612  55.4  64.2  46.0        18.2
12  20160613  58.3  68.2  47.3        20.9
13  20160614  59.7  67.8  47.8        20.0
14  20160615  63.4  70.3  49.3        21.0
15  20160616  57.8  67.5  55.6        11.9
16  20160617  60.4  70.7  55.9        14.8
17  20160618  57.3  62.8  54.0         8.8
18  20160619  56.3  59.2  54.1         5.1
19  20160620  59.3  69.1  52.2        16.9
20  20160621  62.6  71.4  50.4        21.0
21  20160622  61.7  70.2  55.4        14.8
22  2016062

In [19]:
print(data)

[[2.0160601e+07 6.5500000e+01 7.3600000e+01 5.4700000e+01]
 [2.0160602e+07 6.5800000e+01 8.0800000e+01 5.5000000e+01]
 [2.0160603e+07 6.8400000e+01 7.7900000e+01 5.5600000e+01]
 [2.0160604e+07 5.7500000e+01 7.0900000e+01 4.7300000e+01]
 [2.0160605e+07 5.1400000e+01 5.8300000e+01 4.3200000e+01]
 [2.0160606e+07 5.2200000e+01 5.9700000e+01 4.2800000e+01]
 [2.0160607e+07 5.6900000e+01 6.5100000e+01 4.5900000e+01]
 [2.0160608e+07 5.4200000e+01 6.0400000e+01 4.7500000e+01]
 [2.0160609e+07 4.9400000e+01 5.4100000e+01 4.5700000e+01]
 [2.0160610e+07 4.9500000e+01 5.5900000e+01 4.3000000e+01]
 [2.0160611e+07 5.4000000e+01 6.2100000e+01 4.1700000e+01]
 [2.0160612e+07 5.5400000e+01 6.4200000e+01 4.6000000e+01]
 [2.0160613e+07 5.8300000e+01 6.8200000e+01 4.7300000e+01]
 [2.0160614e+07 5.9700000e+01 6.7800000e+01 4.7800000e+01]
 [2.0160615e+07 6.3400000e+01 7.0300000e+01 4.9300000e+01]
 [2.0160616e+07 5.7800000e+01 6.7500000e+01 5.5600000e+01]
 [2.0160617e+07 6.0400000e+01 7.0700000e+01 5.5900000e+0

In [20]:
print(dataFrame.shape)

(30, 5)


In [21]:
print(data.shape)

(30, 4)


In [22]:
print(dataFrame.columns)

Index(['YEARMODA', 'TEMP', 'MAX', 'MIN', 'TEMP_RANGE'], dtype='object')


In [23]:
print(dataFrame.describe())

           YEARMODA       TEMP        MAX        MIN  TEMP_RANGE
count  3.000000e+01  30.000000  30.000000  30.000000    30.00000
mean   2.016062e+07  59.730000  67.940000  51.750000    16.19000
std    8.803408e+00   5.475472   6.651761   5.634484     4.75252
min    2.016060e+07  49.400000  54.100000  41.700000     5.10000
25%    2.016061e+07  56.450000  63.150000  47.300000    12.90000
50%    2.016062e+07  60.050000  69.000000  54.050000    16.90000
75%    2.016062e+07  64.900000  72.375000  55.750000    19.80000
max    2.016063e+07  69.600000  80.800000  60.300000    25.80000


In [24]:
# Pandas
dataFrame['TEMP'].max()

69.6

In [25]:
# NumPy
temp.max()

69.6

# Filtering data

Imagine that we're interested in the days in June with a temperature range of more than 20 degrees Fahrenheit.

In [26]:
# Pandas
dataFrame.loc[dataFrame['TEMP_RANGE'] > 20.0]

YEARMODA  TEMP   MAX   MIN  TEMP_RANGE
1   20160602  65.8  80.8  55.0        25.8
2   20160603  68.4  77.9  55.6        22.3
3   20160604  57.5  70.9  47.3        23.6
10  20160611  54.0  62.1  41.7        20.4
12  20160613  58.3  68.2  47.3        20.9
14  20160615  63.4  70.3  49.3        21.0
20  20160621  62.6  71.4  50.4        21.0

In [27]:
# NumPy

# Make a mask with the condition that temp_range more than 20.0
mask = temp_range > 20.0

# Use mask to check our output
print(date[mask])

[20160602. 20160603. 20160604. 20160611. 20160613. 20160615. 20160621.]


In [28]:
print(temp[mask])

[65.8 68.4 57.5 54.  58.3 63.4 62.6]


Now, imagine that we're interested in the *even* days in June with a temperature range of more than 20 degrees Fahrenheit.

In [29]:
4 / 2

2.0

In [30]:
# The % operator returns the remainder from division
4 % 2

0

In [32]:
# The % operator returns the remainder from division
5 % 2

1

In [33]:
# Pandas
dataFrame.loc[(dataFrame['TEMP_RANGE'] > 20.0) & (dataFrame['YEARMODA'] % 2 == 0)]

YEARMODA  TEMP   MAX   MIN  TEMP_RANGE
1  20160602  65.8  80.8  55.0        25.8
3  20160604  57.5  70.9  47.3        23.6

In [34]:
# NumPy

# Make a mask with the condition that temp_range more than 20.0
mask = (temp_range > 20.0) & (date % 2 == 0)

# Use mask to check our output
print(date[mask])

[20160602. 20160604.]


Now, imagine that we're interested in the *even* days in June **OR** those with a temperature range of more than 20 degrees Fahrenheit.

In [35]:
# Pandas
dataFrame.loc[(dataFrame['TEMP_RANGE'] > 20.0) | (dataFrame['YEARMODA'] % 2 == 0)]

YEARMODA  TEMP   MAX   MIN  TEMP_RANGE
1   20160602  65.8  80.8  55.0        25.8
2   20160603  68.4  77.9  55.6        22.3
3   20160604  57.5  70.9  47.3        23.6
5   20160606  52.2  59.7  42.8        16.9
7   20160608  54.2  60.4  47.5        12.9
9   20160610  49.5  55.9  43.0        12.9
10  20160611  54.0  62.1  41.7        20.4
11  20160612  55.4  64.2  46.0        18.2
12  20160613  58.3  68.2  47.3        20.9
13  20160614  59.7  67.8  47.8        20.0
14  20160615  63.4  70.3  49.3        21.0
15  20160616  57.8  67.5  55.6        11.9
17  20160618  57.3  62.8  54.0         8.8
19  20160620  59.3  69.1  52.2        16.9
20  20160621  62.6  71.4  50.4        21.0
21  20160622  61.7  70.2  55.4        14.8
23  20160624  61.1  68.9  56.7        12.2
25  20160626  69.6  77.7  60.3        17.4
27  20160628  65.4  73.0  55.8        17.2
29  20160630  65.7  72.7  59.2        13.5

In [36]:
# NumPy

# Make a mask with the condition that temp_range more than 20.0
mask = (temp_range > 20.0) | (date % 2 == 0)

# Use mask to check our output
print(date[mask])

[20160602. 20160603. 20160604. 20160606. 20160608. 20160610. 20160611.
 20160612. 20160613. 20160614. 20160615. 20160616. 20160618. 20160620.
 20160621. 20160622. 20160624. 20160626. 20160628. 20160630.]
