In [6]:
def years2sec(time_years):
    """Converts time in years to seconds."""
    time_seconds = time_years * 365.25 * 24 * 60 * 60
    return time_seconds

def millionyears2years(time_ma):
    """Converts time in millions of years to years."""
    time_years = time_ma * 1.0e6
    return time_years

def ma2sec(time_ma):
    """Converts time in millions of years to seconds."""
    time_years = millionyears2years(time_ma)
    time_seconds = years2sec(time_years)
    return time_seconds

In [3]:
years2sec(1)

31557600.0

In [ ]:
ten_years_in_sec = years2sec(10)

In [ ]:
print('There are {0:.1f} seconds in ten years.'.format(ten_years_in_sec))

In [ ]:
print('There are {0:.6e} seconds in ten years.'.format(ten_years_in_sec))

In [7]:
help(ma2sec)

Help on function ma2sec in module __main__:

ma2sec(time_ma)
    Converts time in millions of years to seconds.



In [9]:
time_seconds = ma2sec(10)

In [10]:
print('There are {0:.6e} seconds in 10 million years.'.format(time_seconds))

There are 3.155760e+14 seconds in 10 million years.


In [13]:
5.8 * 1.0e6 * 365.25 * 24 * 60 * 60

183034080000000.0

# NumPy stuff from here down.

In [14]:
import numpy as np

In [16]:
np.random.rand(5)-0.5

array([-0.49527469, -0.28205529,  0.44333704,  0.02274387, -0.13044774])

In [17]:
random_values = np.random.rand(100000) - 0.5

In [18]:
random_values

array([-0.12167667,  0.15520523,  0.46850816, ..., -0.43203858,
       -0.16319597, -0.03078879])

In [22]:
random_values[:10]

array([-0.12167667,  0.15520523,  0.46850816, -0.27693783, -0.32747111,
        0.02502693, -0.25709784, -0.17701304, -0.23009737, -0.08700997])

In [23]:
random_values.min()

-0.4999971703992043

In [24]:
random_values.max()

0.4999989250002378

In [26]:
random_values.mean()

-0.0014710913737995776

In [30]:
random_values[0:1000].max()

0.4976208655918015

In [31]:
random_values > 0.0

array([False,  True,  True, ..., False, False, False])

In [32]:
random_mask = random_values > 0.0

In [33]:
random_values[random_mask]

array([0.15520523, 0.46850816, 0.02502693, ..., 0.26470463, 0.44999563,
       0.27716314])

In [34]:
random_values[random_values > 0.0]

array([0.15520523, 0.46850816, 0.02502693, ..., 0.26470463, 0.44999563,
       0.27716314])

In [35]:
random_values[random_values > 0.0].mean()

0.24849417149425088